[build]
base = "."
command = "CI=false SKIP_PREFLIGHT_CHECK=true npm run build"
publish = "./build/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"